// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testmsg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 集群处于稳定
// 控制台根据玩家id，通过与gameser一样的一致性哈希算法,直接命中节点，并向节点发送消息，让节点在本地执行
// 必须保证senderId与targetId一定在本地节点上
type LocalRun struct {
	ReqId                uint64   `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	SenderId             int64    `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TargetId             int64    `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalRun) Reset()         { *m = LocalRun{} }
func (m *LocalRun) String() string { return proto.CompactTextString(m) }
func (*LocalRun) ProtoMessage()    {}
func (*LocalRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *LocalRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalRun.Unmarshal(m, b)
}
func (m *LocalRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalRun.Marshal(b, m, deterministic)
}
func (m *LocalRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalRun.Merge(m, src)
}
func (m *LocalRun) XXX_Size() int {
	return xxx_messageInfo_LocalRun.Size(m)
}
func (m *LocalRun) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalRun.DiscardUnknown(m)
}

var xxx_messageInfo_LocalRun proto.InternalMessageInfo

func (m *LocalRun) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *LocalRun) GetSenderId() int64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *LocalRun) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *LocalRun) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type LocalRunResponse struct {
	ReplyId              uint64   `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalRunResponse) Reset()         { *m = LocalRunResponse{} }
func (m *LocalRunResponse) String() string { return proto.CompactTextString(m) }
func (*LocalRunResponse) ProtoMessage()    {}
func (*LocalRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *LocalRunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalRunResponse.Unmarshal(m, b)
}
func (m *LocalRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalRunResponse.Marshal(b, m, deterministic)
}
func (m *LocalRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalRunResponse.Merge(m, src)
}
func (m *LocalRunResponse) XXX_Size() int {
	return xxx_messageInfo_LocalRunResponse.Size(m)
}
func (m *LocalRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LocalRunResponse proto.InternalMessageInfo

func (m *LocalRunResponse) GetReplyId() uint64 {
	if m != nil {
		return m.ReplyId
	}
	return 0
}

func init() {
	proto.RegisterType((*LocalRun)(nil), "testmsg.LocalRun")
	proto.RegisterType((*LocalRunResponse)(nil), "testmsg.LocalRunResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x4f, 0x86, 0x30,
	0x10, 0xc6, 0x53, 0x41, 0xfe, 0x9c, 0x83, 0xda, 0xc4, 0x04, 0x74, 0x21, 0x4c, 0x2c, 0x32, 0xe8,
	0x07, 0x70, 0x70, 0x22, 0x31, 0x0e, 0x8d, 0xbb, 0x41, 0x7a, 0x21, 0x26, 0xd8, 0x42, 0xef, 0x18,
	0xfc, 0xf6, 0x6f, 0xa0, 0x6f, 0xc3, 0xf0, 0x6e, 0x7d, 0x7e, 0xbf, 0x34, 0xcf, 0xdd, 0x01, 0x30,
	0x12, 0xb7, 0xb3, 0xb3, 0x6c, 0x65, 0xba, 0xbd, 0xff, 0x68, 0xac, 0x57, 0xc8, 0x3e, 0xec, 0xd0,
	0x4f, 0x6a, 0x35, 0xf2, 0x01, 0x12, 0x87, 0xcb, 0xf7, 0xaf, 0x2e, 0x44, 0x25, 0x9a, 0x58, 0x5d,
	0x3b, 0x5c, 0x3a, 0x2d, 0x9f, 0x20, 0x27, 0x34, 0x1a, 0xdd, 0x66, 0xae, 0x2a, 0xd1, 0x44, 0x2a,
	0xf3, 0xc0, 0x4b, 0xee, 0xdd, 0x88, 0xbc, 0xc9, 0xc8, 0x4b, 0x0f, 0x3a, 0x2d, 0x0b, 0x48, 0x07,
	0x6b, 0x18, 0x0d, 0x17, 0x71, 0x25, 0x9a, 0x5c, 0x85, 0x58, 0x3f, 0xc3, 0x5d, 0xa8, 0x55, 0x48,
	0xb3, 0x35, 0x84, 0xb2, 0x84, 0xcc, 0xe1, 0x3c, 0xfd, 0x1f, 0x03, 0xa4, 0x7b, 0xee, 0xf4, 0xcb,
	0x27, 0xdc, 0x7c, 0x21, 0xf1, 0xbb, 0x35, 0x64, 0x27, 0x94, 0x6f, 0x70, 0x7b, 0xfc, 0x5e, 0x56,
	0x24, 0x96, 0xf7, 0xed, 0x79, 0xa3, 0x36, 0x98, 0xc7, 0xf2, 0x02, 0x85, 0xaa, 0x9f, 0x64, 0xbf,
	0xc2, 0xeb, 0x29, 0x00, 0x00, 0xff, 0xff, 0xba, 0xaa, 0x7d, 0x9b, 0x13, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestConsoleClient is the client API for TestConsole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestConsoleClient interface {
	// 控制台发出消息，让节点在本地执行，不需要actor有响应，但控制台消息本身需要有响应
	LocalRunRequest(ctx context.Context, in *LocalRun, opts ...grpc.CallOption) (*LocalRunResponse, error)
}

type testConsoleClient struct {
	cc *grpc.ClientConn
}

func NewTestConsoleClient(cc *grpc.ClientConn) TestConsoleClient {
	return &testConsoleClient{cc}
}

func (c *testConsoleClient) LocalRunRequest(ctx context.Context, in *LocalRun, opts ...grpc.CallOption) (*LocalRunResponse, error) {
	out := new(LocalRunResponse)
	err := c.cc.Invoke(ctx, "/testmsg.TestConsole/LocalRunRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestConsoleServer is the server API for TestConsole service.
type TestConsoleServer interface {
	// 控制台发出消息，让节点在本地执行，不需要actor有响应，但控制台消息本身需要有响应
	LocalRunRequest(context.Context, *LocalRun) (*LocalRunResponse, error)
}

// UnimplementedTestConsoleServer can be embedded to have forward compatible implementations.
type UnimplementedTestConsoleServer struct {
}

func (*UnimplementedTestConsoleServer) LocalRunRequest(ctx context.Context, req *LocalRun) (*LocalRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalRunRequest not implemented")
}

func RegisterTestConsoleServer(s *grpc.Server, srv TestConsoleServer) {
	s.RegisterService(&_TestConsole_serviceDesc, srv)
}

func _TestConsole_LocalRunRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalRun)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestConsoleServer).LocalRunRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testmsg.TestConsole/LocalRunRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestConsoleServer).LocalRunRequest(ctx, req.(*LocalRun))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestConsole_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testmsg.TestConsole",
	HandlerType: (*TestConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LocalRunRequest",
			Handler:    _TestConsole_LocalRunRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
