// Code generated by protoc-gen-go. DO NOT EDIT.
// source: actor.proto

package actor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation errors at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// actor的引用
// Category,Name,Location可以唯一定位一个actor
type ActorRef struct {
	Category             uint32   `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"` // actor类型
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`          //actor名称
	Location             uint32   `protobuf:"varint,3,opt,name=location,proto3" json:"location,omitempty"` //actor服务器位置
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActorRef) Reset()         { *m = ActorRef{} }
func (m *ActorRef) String() string { return proto.CompactTextString(m) }
func (*ActorRef) ProtoMessage()    {}
func (*ActorRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{0}
}

func (m *ActorRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorRef.Unmarshal(m, b)
}
func (m *ActorRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorRef.Marshal(b, m, deterministic)
}
func (m *ActorRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorRef.Merge(m, src)
}
func (m *ActorRef) XXX_Size() int {
	return xxx_messageInfo_ActorRef.Size(m)
}
func (m *ActorRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorRef.DiscardUnknown(m)
}

var xxx_messageInfo_ActorRef proto.InternalMessageInfo

func (m *ActorRef) GetCategory() uint32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *ActorRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ActorRef) GetLocation() uint32 {
	if m != nil {
		return m.Location
	}
	return 0
}

// 远程消息，投递非本机actor消息时需要序列化成此消息类型
type RemoteMsg struct {
	Sender               *ActorRef `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`                         //发送者actor
	Target               *ActorRef `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`                         //目标actor
	ReqId                int64     `protobuf:"varint,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`             //请求id，对于一些用响应需要的消息，用于追踪请求的
	IsRespond            bool      `protobuf:"varint,4,opt,name=is_respond,json=isRespond,proto3" json:"is_respond,omitempty"` //表明是否为一个响应消息
	MsgName              string    `protobuf:"bytes,5,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`        //消息名称
	MsgData              []byte    `protobuf:"bytes,6,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`        //消息数据
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RemoteMsg) Reset()         { *m = RemoteMsg{} }
func (m *RemoteMsg) String() string { return proto.CompactTextString(m) }
func (*RemoteMsg) ProtoMessage()    {}
func (*RemoteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{1}
}

func (m *RemoteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteMsg.Unmarshal(m, b)
}
func (m *RemoteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteMsg.Marshal(b, m, deterministic)
}
func (m *RemoteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteMsg.Merge(m, src)
}
func (m *RemoteMsg) XXX_Size() int {
	return xxx_messageInfo_RemoteMsg.Size(m)
}
func (m *RemoteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteMsg proto.InternalMessageInfo

func (m *RemoteMsg) GetSender() *ActorRef {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *RemoteMsg) GetTarget() *ActorRef {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *RemoteMsg) GetReqId() int64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *RemoteMsg) GetIsRespond() bool {
	if m != nil {
		return m.IsRespond
	}
	return false
}

func (m *RemoteMsg) GetMsgName() string {
	if m != nil {
		return m.MsgName
	}
	return ""
}

func (m *RemoteMsg) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func init() {
	proto.RegisterType((*ActorRef)(nil), "actor.ActorRef")
	proto.RegisterType((*RemoteMsg)(nil), "actor.RemoteMsg")
}

func init() { proto.RegisterFile("actor.proto", fileDescriptor_93a2698287ded216) }

var fileDescriptor_93a2698287ded216 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x89, 0xbb, 0xad, 0xed, 0xac, 0x22, 0x04, 0x84, 0x28, 0x08, 0x65, 0x2f, 0xf6, 0xb4,
	0x07, 0xfd, 0x05, 0x82, 0x17, 0x0f, 0x7a, 0xc8, 0xc1, 0x6b, 0x19, 0x9b, 0x31, 0x14, 0x6c, 0xb3,
	0x3b, 0x99, 0x8b, 0x3f, 0xd1, 0x7f, 0x25, 0x9d, 0xee, 0x7a, 0xf2, 0xf6, 0x5e, 0xde, 0x47, 0x5e,
	0x5e, 0x60, 0x83, 0xbd, 0x24, 0xde, 0xed, 0x39, 0x49, 0xb2, 0x85, 0x9a, 0xed, 0x3b, 0x54, 0x4f,
	0xb3, 0xf0, 0xf4, 0x69, 0x6f, 0xa1, 0xea, 0x51, 0x28, 0x26, 0xfe, 0x76, 0xa6, 0x31, 0xed, 0xa5,
	0xff, 0xf3, 0xd6, 0xc2, 0x7a, 0xc2, 0x91, 0xdc, 0x59, 0x63, 0xda, 0xda, 0xab, 0x9e, 0xf9, 0xaf,
	0xd4, 0xa3, 0x0c, 0x69, 0x72, 0xab, 0x85, 0x3f, 0xf9, 0xed, 0x8f, 0x81, 0xda, 0xd3, 0x98, 0x84,
	0x5e, 0x73, 0xb4, 0xf7, 0x50, 0x66, 0x9a, 0x02, 0xb1, 0xde, 0xbb, 0x79, 0xb8, 0xda, 0x2d, 0x4f,
	0x39, 0x55, 0xfb, 0x63, 0x3c, 0x83, 0x82, 0x1c, 0x49, 0xb4, 0xe8, 0x3f, 0x70, 0x89, 0xed, 0x35,
	0x94, 0x4c, 0x87, 0x6e, 0x08, 0xda, 0xbc, 0xf2, 0x05, 0xd3, 0xe1, 0x25, 0xd8, 0x3b, 0x80, 0x21,
	0x77, 0x4c, 0x79, 0x9f, 0xa6, 0xe0, 0xd6, 0x8d, 0x69, 0x2b, 0x5f, 0x0f, 0xd9, 0x2f, 0x07, 0xf6,
	0x06, 0xaa, 0x31, 0xc7, 0x4e, 0x97, 0x14, 0xba, 0xe4, 0x7c, 0xcc, 0xf1, 0x6d, 0x1e, 0x73, 0x8c,
	0x02, 0x0a, 0xba, 0xb2, 0x31, 0xed, 0x85, 0x46, 0xcf, 0x28, 0xf8, 0x51, 0xea, 0x8f, 0x3d, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x91, 0x05, 0x19, 0x19, 0x40, 0x01, 0x00, 0x00,
}
