// Code generated by protoc-gen-go. DO NOT EDIT.
// source: actor.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActorDesc struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	System               string   `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActorDesc) Reset()         { *m = ActorDesc{} }
func (m *ActorDesc) String() string { return proto.CompactTextString(m) }
func (*ActorDesc) ProtoMessage()    {}
func (*ActorDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{0}
}

func (m *ActorDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorDesc.Unmarshal(m, b)
}
func (m *ActorDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorDesc.Marshal(b, m, deterministic)
}
func (m *ActorDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorDesc.Merge(m, src)
}
func (m *ActorDesc) XXX_Size() int {
	return xxx_messageInfo_ActorDesc.Size(m)
}
func (m *ActorDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorDesc.DiscardUnknown(m)
}

var xxx_messageInfo_ActorDesc proto.InternalMessageInfo

func (m *ActorDesc) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActorDesc) GetSystem() string {
	if m != nil {
		return m.System
	}
	return ""
}

// 重定向消息
type RedirectInfo struct {
	NodeKey              string   `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	NodeStatus           int32    `protobuf:"varint,2,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectInfo) Reset()         { *m = RedirectInfo{} }
func (m *RedirectInfo) String() string { return proto.CompactTextString(m) }
func (*RedirectInfo) ProtoMessage()    {}
func (*RedirectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{1}
}

func (m *RedirectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectInfo.Unmarshal(m, b)
}
func (m *RedirectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectInfo.Marshal(b, m, deterministic)
}
func (m *RedirectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectInfo.Merge(m, src)
}
func (m *RedirectInfo) XXX_Size() int {
	return xxx_messageInfo_RedirectInfo.Size(m)
}
func (m *RedirectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectInfo proto.InternalMessageInfo

func (m *RedirectInfo) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *RedirectInfo) GetNodeStatus() int32 {
	if m != nil {
		return m.NodeStatus
	}
	return 0
}

type WrapMsg struct {
	MsgType              string   `protobuf:"bytes,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgData              []byte   `protobuf:"bytes,2,opt,name=msg_data,json=msgData,proto3" json:"msg_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrapMsg) Reset()         { *m = WrapMsg{} }
func (m *WrapMsg) String() string { return proto.CompactTextString(m) }
func (*WrapMsg) ProtoMessage()    {}
func (*WrapMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{2}
}

func (m *WrapMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrapMsg.Unmarshal(m, b)
}
func (m *WrapMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrapMsg.Marshal(b, m, deterministic)
}
func (m *WrapMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapMsg.Merge(m, src)
}
func (m *WrapMsg) XXX_Size() int {
	return xxx_messageInfo_WrapMsg.Size(m)
}
func (m *WrapMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapMsg.DiscardUnknown(m)
}

var xxx_messageInfo_WrapMsg proto.InternalMessageInfo

func (m *WrapMsg) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *WrapMsg) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

// 请求消息
type RequestMsg struct {
	Sender               *ActorDesc    `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Target               *ActorDesc    `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ReqId                uint64        `protobuf:"varint,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Redirect             *RedirectInfo `protobuf:"bytes,4,opt,name=redirect,proto3" json:"redirect,omitempty"`
	IsRespond            bool          `protobuf:"varint,5,opt,name=is_respond,json=isRespond,proto3" json:"is_respond,omitempty"`
	Data                 *WrapMsg      `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RequestMsg) Reset()         { *m = RequestMsg{} }
func (m *RequestMsg) String() string { return proto.CompactTextString(m) }
func (*RequestMsg) ProtoMessage()    {}
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{3}
}

func (m *RequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMsg.Unmarshal(m, b)
}
func (m *RequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMsg.Marshal(b, m, deterministic)
}
func (m *RequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMsg.Merge(m, src)
}
func (m *RequestMsg) XXX_Size() int {
	return xxx_messageInfo_RequestMsg.Size(m)
}
func (m *RequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMsg proto.InternalMessageInfo

func (m *RequestMsg) GetSender() *ActorDesc {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *RequestMsg) GetTarget() *ActorDesc {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *RequestMsg) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *RequestMsg) GetRedirect() *RedirectInfo {
	if m != nil {
		return m.Redirect
	}
	return nil
}

func (m *RequestMsg) GetIsRespond() bool {
	if m != nil {
		return m.IsRespond
	}
	return false
}

func (m *RequestMsg) GetData() *WrapMsg {
	if m != nil {
		return m.Data
	}
	return nil
}

// 响应消息
type ResponseMsg struct {
	Resper               *ActorDesc `protobuf:"bytes,1,opt,name=resper,proto3" json:"resper,omitempty"`
	ReqId                uint64     `protobuf:"varint,2,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Data                 *WrapMsg   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResponseMsg) Reset()         { *m = ResponseMsg{} }
func (m *ResponseMsg) String() string { return proto.CompactTextString(m) }
func (*ResponseMsg) ProtoMessage()    {}
func (*ResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{4}
}

func (m *ResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMsg.Unmarshal(m, b)
}
func (m *ResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMsg.Marshal(b, m, deterministic)
}
func (m *ResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMsg.Merge(m, src)
}
func (m *ResponseMsg) XXX_Size() int {
	return xxx_messageInfo_ResponseMsg.Size(m)
}
func (m *ResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMsg proto.InternalMessageInfo

func (m *ResponseMsg) GetResper() *ActorDesc {
	if m != nil {
		return m.Resper
	}
	return nil
}

func (m *ResponseMsg) GetReqId() uint64 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ResponseMsg) GetData() *WrapMsg {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ActorDesc)(nil), "pb.ActorDesc")
	proto.RegisterType((*RedirectInfo)(nil), "pb.RedirectInfo")
	proto.RegisterType((*WrapMsg)(nil), "pb.WrapMsg")
	proto.RegisterType((*RequestMsg)(nil), "pb.RequestMsg")
	proto.RegisterType((*ResponseMsg)(nil), "pb.ResponseMsg")
}

func init() { proto.RegisterFile("actor.proto", fileDescriptor_93a2698287ded216) }

var fileDescriptor_93a2698287ded216 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x6b, 0xe3, 0x30,
	0x10, 0x85, 0xb1, 0x93, 0x38, 0xf1, 0x38, 0xc9, 0x2e, 0x82, 0x5d, 0xbc, 0x0b, 0x25, 0xc6, 0x50,
	0x30, 0xa5, 0xe4, 0x90, 0x1c, 0x7b, 0x28, 0x85, 0x5c, 0xd2, 0xd2, 0x8b, 0x52, 0xe8, 0xd1, 0x28,
	0xd6, 0xd4, 0x98, 0xd6, 0xb6, 0x22, 0x29, 0x05, 0xff, 0xda, 0xfe, 0x95, 0x22, 0xd9, 0x0e, 0x81,
	0x92, 0xe3, 0xcc, 0x9b, 0xf9, 0x34, 0xef, 0x21, 0x08, 0x58, 0xa6, 0x6b, 0xb9, 0x14, 0xb2, 0xd6,
	0x35, 0x71, 0xc5, 0x3e, 0x5e, 0x83, 0xff, 0x60, 0x5a, 0x1b, 0x54, 0x19, 0x99, 0x83, 0x5b, 0xf0,
	0xd0, 0x89, 0x9c, 0x64, 0x40, 0xdd, 0x82, 0x93, 0xbf, 0xe0, 0xa9, 0x46, 0x69, 0x2c, 0x43, 0x37,
	0x72, 0x12, 0x9f, 0x76, 0x55, 0xfc, 0x08, 0x53, 0x8a, 0xbc, 0x90, 0x98, 0xe9, 0x6d, 0xf5, 0x56,
	0x93, 0x7f, 0x30, 0xa9, 0x6a, 0x8e, 0xe9, 0x3b, 0x36, 0x76, 0xdb, 0xa7, 0x63, 0x53, 0x3f, 0x61,
	0x43, 0x16, 0x10, 0x58, 0x49, 0x69, 0xa6, 0x8f, 0xca, 0x72, 0x46, 0x14, 0x4c, 0x6b, 0x67, 0x3b,
	0xf1, 0x3d, 0x8c, 0x5f, 0x25, 0x13, 0xcf, 0x2a, 0x37, 0x98, 0x52, 0xe5, 0xa9, 0x6e, 0x04, 0xf6,
	0x98, 0x52, 0xe5, 0x2f, 0x8d, 0xc0, 0x5e, 0xe2, 0x4c, 0x33, 0xcb, 0x98, 0x5a, 0x69, 0xc3, 0x34,
	0x8b, 0xbf, 0x1c, 0x00, 0x8a, 0x87, 0x23, 0x2a, 0x6d, 0x20, 0xd7, 0xe0, 0x29, 0xac, 0x38, 0x4a,
	0x8b, 0x08, 0x56, 0xb3, 0xa5, 0xd8, 0x2f, 0x4f, 0x16, 0x69, 0x27, 0x9a, 0x31, 0xcd, 0x64, 0x8e,
	0xda, 0xe2, 0x7e, 0x8e, 0xb5, 0x22, 0xf9, 0x03, 0x9e, 0xc4, 0x43, 0x5a, 0xf0, 0x70, 0x10, 0x39,
	0xc9, 0x90, 0x8e, 0x24, 0x1e, 0xb6, 0x9c, 0xdc, 0xc2, 0x44, 0x76, 0x01, 0x84, 0x43, 0xbb, 0xff,
	0xdb, 0xec, 0x9f, 0x87, 0x42, 0x4f, 0x13, 0xe4, 0x0a, 0xa0, 0x50, 0xa9, 0x44, 0x25, 0xea, 0x8a,
	0x87, 0xa3, 0xc8, 0x49, 0x26, 0xd4, 0x2f, 0x14, 0x6d, 0x1b, 0x64, 0x01, 0x43, 0xeb, 0xcb, 0xb3,
	0xa0, 0xc0, 0x80, 0xba, 0x44, 0xa8, 0x15, 0xe2, 0x0f, 0x08, 0xda, 0x59, 0x85, 0x9d, 0x43, 0xc3,
	0xba, 0xe8, 0xb0, 0x15, 0xcf, 0x4e, 0x77, 0xcf, 0x4f, 0xef, 0x5f, 0x1b, 0x5c, 0x78, 0x6d, 0x75,
	0x07, 0x33, 0x8a, 0x65, 0xad, 0x71, 0x87, 0xf2, 0xb3, 0xc8, 0x90, 0xdc, 0xc0, 0xb8, 0xcb, 0x97,
	0xcc, 0x5b, 0x97, 0x7d, 0xd8, 0xff, 0x7f, 0xb5, 0xf5, 0xe9, 0xb6, 0xbd, 0x67, 0x7f, 0xd6, 0xfa,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x31, 0xb0, 0x5c, 0x80, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteServiceClient is the client API for RemoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteServiceClient interface {
	Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ResponseMsg, error)
}

type remoteServiceClient struct {
	cc *grpc.ClientConn
}

func NewRemoteServiceClient(cc *grpc.ClientConn) RemoteServiceClient {
	return &remoteServiceClient{cc}
}

func (c *remoteServiceClient) Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ResponseMsg, error) {
	out := new(ResponseMsg)
	err := c.cc.Invoke(ctx, "/pb.RemoteService/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteServiceServer is the server API for RemoteService service.
type RemoteServiceServer interface {
	Request(context.Context, *RequestMsg) (*ResponseMsg, error)
}

// UnimplementedRemoteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteServiceServer struct {
}

func (*UnimplementedRemoteServiceServer) Request(ctx context.Context, req *RequestMsg) (*ResponseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}

func RegisterRemoteServiceServer(s *grpc.Server, srv RemoteServiceServer) {
	s.RegisterService(&_RemoteService_serviceDesc, srv)
}

func _RemoteService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RemoteService/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).Request(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RemoteService",
	HandlerType: (*RemoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _RemoteService_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "actor.proto",
}
